// User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const MARK_NOTIFCATIONS_READ = "MARK_NOTIFCATIONS_READ";
// UI reducer types
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_DATA = "LOADING_DATA";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
// Data reducer types
export const SET_TASKS = "SET_ANNOUNCEMENTS";
export const SET_TASK = "SET_ANNOUNCEMENT";
export const APPEND_IMAGEURL_TO_ANNOUNCEMENT = "APPEND_IMAGEURL_TO_ANNOUNCEMENT";
export const COMPLETE_TASK = "LIKE_ANNOUNCEMENT";
export const UNDO_COMPLETE_TASK = "UNLIKE_ANNOUNCEMENT";
export const DELETE_TASK = "DELETE_ANNOUNCEMENT";
export const POST_TASK = "POST_ANNOUNCEMENT";
export const SUBMIT_COMMENT = "SUBMIT_COMMENT";